# Generated by Django 4.2 on 2023-04-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255)),
                ('introduction', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('TMC', '트랜스매스큘린'), ('TFM', '트랜스페미닌'), ('ANG', '안드로진'), ('BIG', '바이젠더'), ('DEMG', '데미젠더'), ('AG', '에이젠더'), ('GL', '젠더리스'), ('NT', '뉴트로이스'), ('TG', '트라이젠더'), ('PG', '폴리젠더'), ('PNG', '펜젠더'), ('GF', '젠더플루이드'), ('GFX', '젠더플럭스'), ('ECT', '기타'), ('RTR', '응답거부')], max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
