# Generated by Django 4.2 on 2023-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('TMC', '트랜스매스큘린'), ('TFM', '트랜스페미닌'), ('ANG', '안드로진'), ('BIG', '바이젠더'), ('DEMG', '데미젠더'), ('AG', '에이젠더'), ('GL', '젠더리스'), ('NT', '뉴트로이스'), ('TG', '트라이젠더'), ('PG', '폴리젠더'), ('PNG', '펜젠더'), ('GF', '젠더플루이드'), ('GFX', '젠더플럭스'), ('ECT', '기타'), ('RTR', '응답거부')], max_length=255),
        ),
    ]
