# Generated by Django 4.2 on 2023-04-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='completion_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
