# Generated by Django 4.2 on 2023-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_completion_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='completion_at',
            field=models.DateTimeField(null=True),
        ),
    ]
